### ISSUE TITLE
Size/ dimensons of images

### ISSUE THREAD

**Issue by kharanshu2** [mdciri/YOLOv7-GRAZPEDWRI-DX#3]
First of all great work. Secondly I tested inference on random images but sometimes it fails to detect clear fractures, is it possible that algorithm prefers certain dimensions, size or resolution of images? Or even certain types of bones found in body?

**Comment by mdciri** [comment]
YOLOv7 is trained and performs inference on images with size 640 x 640. The dataset contains X-ray images of patients of pediatric age, so if you test the model on adult images, the bones are quite different as also the type of fracture.

**Comment by kharanshu2** [comment]
TYSM for replying, it seems to work almost perfectly when i resize image to 640x640.

**Comment by kharanshu2** [comment]
Also now I have done extensive testing on the model and and found only 3 labels majorly, metal, fracture and text, I went out of my way to get examples for lesion and other labels but never occurred.
